# Parameter file
#

# Webserver_apache_role_parameters
#
#
#i_name: "Auto_kubernetes_slave"    # Instance name
#key: "newkey"                      # Instance keyfile name
#i_type: "t2.micro"                 # Instance type
#img: 'ami-08e0ca9924195beba'       # AMI iD
#subnet: 'subnet-3bb8bd53'          # Subnet ID
#sg: 'sg-0a238838d3301e9dc'         # Security Group ID
#counts: 1                          # Instance Count
#zone: 'ap-south-1'                 # Regon
#grp_tag: "k8sSlaveaa"              # Inventory Group Tag ( This is stored in inventory as group tag. Use these tag as host for further automation work )

inventory_path: "./inventory"       # Inventory path

#tag: "k8sSlave"                    # required Special Tag
#ssh_key_full_path: "/home/ec2-user/newkey.pem"    # Ansible ssh private key path
#
# access_pass: xxxxxxxxxxxxxxx     # Enter your aws acess-key in vault Secret.yml
# secret_pass: xxxxxxxxxxxxxxx     # Enter your aws  secret key in vault Secret.yml
#

# kubernetes master node setup role Parameters
#
cidr: 10.240.0.0



# kubernetes master node setup role Parameters
#



# Mysql Parameters
#
mysql_pod_name: "mypod"
db_root_pass: "Root"
db_user: "kush"
db_pass: "any"
db_name: "wp"


# Wordpress Parameters
#
wp_pod_name: "mywp"
nodePort: "31001"       # Must be in range 30000-32500


# Other Parameters
clear_inventory: "yes"
